services:
  ssh-exporter:
    image: ssh-audit-exporter
    container_name: ssh-exporter

    user: root

    ports:
      - "9100:9100"
      
    environment:
      SSH_LOG_TYPE: journal

    # Load ohne rules ;) or use default rule set
    # command:
    #  - --rule=success:ssh_success:Accepted .* for (\w+) from ([0-9.]+)
    #  - --rule=fail:ssh_failed:Failed .* for (\w+) from ([0-9.]+)
    #  - --rule=info:su_session:session (opened|closed) for user (\w+)
    #  - --rule=info:disconnect:Disconnected from user (\w+)

    volumes:
      - /var/log/journal:/var/log/journal:ro
      - /run/systemd/journal:/run/systemd/journal:ro
      - /etc/machine-id:/etc/machine-id:ro

    env_file:
      - .env

    restart: unless-stopped