services:
  ssh-exporter:
    image: ssh-audit-exporter
    container_name: ssh-exporter

    ports:
      - "9100:9100"

    environment:
      SSH_LOG_TYPE: journal

    volumes:
      - /run/systemd/journal/socket:/run/systemd/journal/socket:ro
      - /run/log/journal:/run/log/journal:ro
      - /usr/bin/journalctl:/usr/bin/journalctl:ro

    env_file:
      - .env

    restart: unless-stopped